spring:
  
  application:
      name: java-springboot3-course

  config:
    import: env.properties

  datasource:
    driver-class-name: ${DRIVER}
    url: ${URL} 
    username: ${USER_NAME} 
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      #properties:
        #hibernate:
          #dialect: ${HIBERNATE_ORA_DIALECT}
    show-sql: false
    open-in-view: true

